# This is a basic workflow to help you get started with Actions

name: Linting

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: rahul-deepsource/pyaction@1.4.0
        with:
          use-pylint: false
          use-pycodestyle: false
          use-flake8: false
          use-mypy: false
          use-vulture: false
